apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: video-automation
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: your-registry/video-automation-backend:latest
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3001"
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: POSTGRES_HOST
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: POSTGRES_PASSWORD
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: video-automation
spec:
  selector:
    app: backend
  ports:
  - port: 80
    targetPort: 3001
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: video-automation
data:
  POSTGRES_HOST: "postgres"
  POSTGRES_DB: "video_automation"
  MONGODB_URI: "mongodb://mongodb:27017/video_automation"
  REDIS_HOST: "redis"
  RABBITMQ_URL: "amqp://rabbitmq:5672"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: video-automation
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=  # postgres (base64 encoded)
  POSTGRES_PASSWORD: cG9zdGdyZXM=  # postgres (base64 encoded)
  JWT_SECRET: eW91ci1qd3Qtc2VjcmV0LWtleQ==  # your-jwt-secret-key (base64 encoded)
