apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: video-automation
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: your-registry/video-automation-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: NEXT_PUBLIC_API_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: NEXT_PUBLIC_API_URL
        - name: NEXTAUTH_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: NEXTAUTH_URL
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: frontend-secrets
              key: NEXTAUTH_SECRET
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "300m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: video-automation
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: video-automation
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - app.video-automation.com
    secretName: frontend-tls
  rules:
  - host: app.video-automation.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: video-automation
data:
  NEXT_PUBLIC_API_URL: "https://api.video-automation.com"
  NEXTAUTH_URL: "https://app.video-automation.com"
  NEXT_PUBLIC_SOCKET_URL: "wss://api.video-automation.com"
---
apiVersion: v1
kind: Secret
metadata:
  name: frontend-secrets
  namespace: video-automation
type: Opaque
data:
  NEXTAUTH_SECRET: eW91ci1uZXh0YXV0aC1zZWNyZXQ=  # your-nextauth-secret (base64 encoded)
